In [4]:
import numpy as np
#numpy array: 连续存储，单一数据类型
#build numpy array and get its attribute: ndim, dtype
array1 = np.random.random((4,6))
print(array1)
print("shape: {}, size: {}, ndim: {}, datatype: {}".format(array1.shape, array1.size, array1.ndim, array1.dtype))


[[0.86173905 0.78949908 0.90074774 0.21023779 0.90753385 0.37766037]
 [0.83612181 0.07065745 0.20458992 0.04967077 0.69893116 0.12720572]
 [0.78396055 0.95629857 0.3720273  0.81808391 0.44137928 0.13169722]
 [0.83788495 0.7698047  0.19280218 0.2498486  0.70863364 0.76165279]]
shape: (4, 6), size: 24, ndim: 2, datatype: float64


In [5]:
#change shape: reshape(), ravel(), flatten() #only flatten() is a copy instead of view
#convert array1 into shape(3,8)
array1_view_reshape = array1.reshape(3,8) #just a view not a copy
print(array1_view_reshape)
array1_flatten_copy = array1.flatten() #ravel(), reshape(-1) also work, but just get a view
print(array1_flatten_copy)


[[0.86173905 0.78949908 0.90074774 0.21023779 0.90753385 0.37766037
  0.83612181 0.07065745]
 [0.20458992 0.04967077 0.69893116 0.12720572 0.78396055 0.95629857
  0.3720273  0.81808391]
 [0.44137928 0.13169722 0.83788495 0.7698047  0.19280218 0.2498486
  0.70863364 0.76165279]]
[0.86173905 0.78949908 0.90074774 0.21023779 0.90753385 0.37766037
 0.83612181 0.07065745 0.20458992 0.04967077 0.69893116 0.12720572
 0.78396055 0.95629857 0.3720273  0.81808391 0.44137928 0.13169722
 0.83788495 0.7698047  0.19280218 0.2498486  0.70863364 0.76165279]


In [8]:
#horizontal or vertical stack(opposite:hsplit(matrix, breakpotints_index_list))
#copy not view
matrix_a = np.random.randint(0, 10, (4,4))
print("matrix_a:")
print(matrix_a)
matrix_b= np.random.randint(10, size=(4,4))
print("matrix_b:")
print(matrix_b)
#np.hsatck([a, b]), np.c_[]
#h_result = np.hstack([matrix_a,matrix_b]) 
h_result = np.c_[matrix_a, matrix_b]
print(h_result)
#np.vstack([a, b]), np.r_[]
#v_result = np.vstack([matrix_a,matrix_b]) 
v_result = np.r_[matrix_a, matrix_b]
print(v_result)


matrix_a:
[[4 6 0 5]
 [7 1 2 8]
 [4 3 2 7]
 [4 5 4 4]]
matrix_b:
[[3 4 5 5]
 [6 4 8 7]
 [7 1 4 7]
 [1 7 8 1]]
[[4 6 0 5 3 4 5 5]
 [7 1 2 8 6 4 8 7]
 [4 3 2 7 7 1 4 7]
 [4 5 4 4 1 7 8 1]]
[[4 6 0 5]
 [7 1 2 8]
 [4 3 2 7]
 [4 5 4 4]
 [3 4 5 5]
 [6 4 8 7]
 [7 1 4 7]
 [1 7 8 1]]


In [9]:
#slice(just view not a copy)
#切片赋值
#创建一个周围全1中间全0的16*16数组
matrix = np.zeros((16,16))

#set elements of the first row all 1
matrix[0,:] = 1 #element-wise operation
#set elements of the last row all 1
matrix[15, :] = 1

#set elements of the first column all 1
matrix[:,0] = 1 #element-wise operation
#set elements of the last column all 1
matrix[:, 15] = 1

print(matrix)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [12]:
#Normalization of array
array_orig = np.random.randint(100, size=10000)
print(array_orig)
#Zero Normalization
mean, var, std = array_orig.mean(), array_orig.var(),array_orig.std()#get mean, var, std
print("mean: {}, var: {}, std: {}".format(mean, var, std))
array_norm1 = (array_orig-mean) / std
print(array_norm1)
#Min-max Normalization
max_idx = np.argmax(array_orig)
min_idx = np.argmin(array_orig)
max_v, min_v = array_orig[max_idx], array_orig[min_idx]
print("max: {}, loc: {}".format(max_v, max_idx))
print("min: {}, loc: {}".format(min_v, min_idx))
array_norm2 = (array_orig-min_v) / (max_v-min_v)
print(array_norm2)

[84 93 31 ... 93 37 63]
mean: 49.119, var: 840.0102390000001, std: 28.982930131372157
[ 1.2035015   1.51402911 -0.62516108 ...  1.51402911 -0.41814268
  0.47893708]
max: 99, loc: 126
min: 0, loc: 102
[0.84848485 0.93939394 0.31313131 ... 0.93939394 0.37373737 0.63636364]


In [15]:
#Bool hidden mask
scores = np.random.randint(80, 100, 30)
print("All scores:", scores)
#get scores >= 95
print("Scores >= 95:", scores[scores>=95])
#get scores <= 85
print("Scores <= 85:", scores[scores<=85])
#get scores in (85,95)
print("Scores in (85,95):", scores[(scores>85) & (scores<95)]) #op1 & op2 ->ops need ()
#two ways to sort
#np.sory(scores) returns a sorted array, doesn't change scores itself
scores_sorted = np.sort(scores)
print(scores_sorted)
#scores.sort() changes itself
scores.sort()
print(scores)

All scores: [90 82 94 82 84 89 99 99 84 98 92 83 80 93 81 92 93 90 86 85 98 96 85 90
 96 85 92 90 81 82]
Scores >= 95: [99 99 98 98 96 96]
Scores <= 85: [82 82 84 84 83 80 81 85 85 85 81 82]
Scores in (85,95): [90 94 89 92 93 92 93 90 86 90 92 90]
[80 81 81 82 82 82 83 84 84 85 85 85 86 89 90 90 90 90 92 92 92 93 93 94
 96 96 98 98 99 99]
[80 81 81 82 82 82 83 84 84 85 85 85 86 89 90 90 90 90 92 92 92 93 93 94
 96 96 98 98 99 99]


In [18]:
#compare time of multiply using Python For and Numpy
#ipython provides %timeit func()
a = np.arange(9).reshape(3,3)
b = np.arange(9).reshape(3,3)


def mul_elewise(a, b):
    ##element-wise multipy: a*b
    if (a.shape != b.shape):
        #can't operate under this condition
        return
    result = np.zeros(a.shape)
    rows, cols = a.shape    
    for i in range(rows):
        for j in range(cols):
            result[i][j] = a[i][j] * b[i][j]
    
    return result


def mul_matrix(a,b):
    #矩阵乘法
    #result[i][j] = sum( a[i][m]*b[m][j] for m=0 to a.shape[1] or b.shape[0] )
    if(a.shape[1] != b.shape[0]):
        #can't operate under this condition
        return
    rows, mids = a.shape
    cols =b.shape[1]
    result = np.zeros( (rows, cols) )
    for i in range(rows):
        for j in range(cols):
            for m in range(mids):
                result += a[i][m] * b[m][j]
    
    return result

#compare element-wise multipy
print("Element-wise multipy")
%timeit mul_elewise(a, b)
%timeit a*b

#compare matrix multiply
print("Matrix multiply")
%timeit mul_matrix(a, b)
%timeit np.dot(a, b)
    


Element-wise multipy
10.8 µs ± 19.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
565 ns ± 0.562 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
Matrix multiply
101 µs ± 123 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
1.17 µs ± 5.91 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
